openapi: 3.0.0
info:
  title: Formula Student Telemetry API
  description: API documentation for telemetry data (speed, temperature, RPM, etc.)
  version: 1.0.0

servers:
  - url: http://localhost:3000

paths:
  /api/data:
    get:
      summary: Get all telemetry data
      description: Returns all the latest sensor readings
      responses:
        '200':
          description: Successful response

  /api/speed:
    get:
      summary: Get current speed
      description: Returns the latest vehicle speed
      responses:
        '200':
          description: Speed in km/h

  /api/speed/history:
    get:
      summary: Get speed history
      description: Returns a history of speed values over time
      responses:
        '200':
          description: Array of speed readings

  /api/temperature:
    get:
      summary: Get temperature reading
      description: Returns the latest temperature sensor value
      responses:
        '200':
          description: Temperature in Celsius

  /api/rpm:
    get:
      summary: Get current RPM
      description: Returns the current engine RPM
      responses:
        '200':
          description: Revolutions per minute

  /api/fuel:
    get:
      summary: Get current fuel data
      description: Returns level, volume, status, estimatedRange, timestamp.
      responses:
        '200':
          description: Fuel data object
          content:
            application/json:
              schema:
                type: object
                properties:
                  level:
                    type: number
                    format: float
                    description: Fuel percentage (0–100)
                  unit:
                    type: string
                    example: '%'
                  volume:
                    type: number
                    format: float
                    description: Volume in liters
                  status:
                    type: string
                    example: 'LOW'
                  estimatedRange:
                    type: integer
                    description: Estimated range in km
                  timestamp:
                    type: string
                    format: date-time

  /api/acceleration:
    get:
      summary: Get current acceleration
      description: Calculates acceleration (m/s²) from last two RPM readings.
      responses:
        '200':
          description: Acceleration data
          content:
            application/json:
              schema:
                type: object
                properties:
                  acceleration:
                    type: number
                    format: float
                    description: m/s²
                  unit:
                    type: string
                    example: 'm/s²'
                  from:
                    type: string
                    format: date-time
                    description: Timestamp of older reading
                  to:
                    type: string
                    format: date-time
                    description: Timestamp of most recent reading
        '404':
          description: Not enough data
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: 'Not enough RPM data to compute acceleration'
